### ISSUE TITLE
Annoying errors getting logged in the error log

### ISSUE THREAD

**Issue by Mark-H** [modmore/SimpleCart_Authorize.Net#3]
- Could not load class: simplecart_authorizenet from simplecart_authorizenet.
- Problem getting service simplecart_authorizenet, instance of class simplecart_authorizenet, from path

**Comment by matdave** [comment]
haha, I just came to check on this error too.. is there a dummy class we can put in there?

**Comment by Mark-H** [comment]
Addressed in 2.0
