### ISSUE TITLE
Random issue with no postback data

### ISSUE THREAD

**Issue by matdave** [modmore/SimpleCart_Authorize.Net#4]
I am currently researching this, but unfortunately have little information to go off of currently. I just found an issue with 2 out of my first 100 orders receiving no postback from authorize.net even though it processed correctly.  Lost $4500 in sales due to it, so will keep investigating why the order didn't finalize after payment completed.

**Comment by matdave** [comment]
After further research, this is apparently just a _thing_ with SIM. It can apparently fail to post back based on a variety of circumstances.

**Comment by Mark-H** [comment]
Any references for your research in case the issue pops up in the future and it requires diving in again?

**Comment by matdave** [comment]
https://support.authorize.net/authkb/index?page=content&id=A663 

> If Relay Response errors occur on rare occasion, but the bulk of your transactions process without problems, then your network might have had a temporary lag or connection failure. These sorts of issues would be outside Authorize.Net's control, but should also be very rare as long as your network is generally stable and reliable.
