### ISSUE TITLE
SIM being deprecated

### ISSUE THREAD

**Issue by matdave** [modmore/SimpleCart_Authorize.Net#5]
Authorize.net has killed SIM over the past few months, and has a direct replacement called "Accept Hosted".  Accept Hosted is pretty sweet, but not an easy swap.  I'm going to be working on an Accept Hosted payment method integration, and would issue notice that Authorize.net is working on a deprecation timeline for SIM.

**Comment by Mark-H** [comment]
Er, I don't think they actually killed it, did they? From what I know they've been moving all their stuff to a new REST API (+ the Accept.js library for on-site credit cards, which is nice) but they're not actually killing anything off?

**Comment by Mark-H** [comment]
According to https://developer.authorize.net/api/upgrade_guide/ you're right: 

> SIM | Deprecated | Use Accept Hosted

They're not mentioning any end of life date for it yet, so it's probably safe to use for the time being. Moving to Accept.js (their listed alternative for DPM, which didn't work for SimpleCart as it requires a post to the server to checkout) would probably be the ideal-est.

**Comment by matdave** [comment]
They "killed" it in that they stripped down the checkout form to bare necessities with minimal customization a couple months ago.

**Comment by Mark-H** [comment]
2.0 uses accept.js.
